CREATE DATABASE equipe;

USE equipe;

CREATE TABLE titulaire(
    id SMALLINT PRIMARY KEY AUTO_INCREMENT,
    nom VARCHAR (20) NOT NULL ,
    ddn VARCHAR (20) NOT NULL,
    ldn VARCHAR (20) NOT NULL,
    club VARCHAR (20) NOT NULL,
    photo VARCHAR (300) NOT NULL,
    poste VARCHAR (40)  NOT NULL
)
ENGINE=INNO_DB;

CREATE TABLE match(
    id SMALLINT PRIMARY KEY AUTO_INCREMENT,
    ddm VARCHAR (20) NOT NULL ,
    hdm VARCHAR (20) NOT NULL,
    score VARCHAR () NOT NULL,
    categorie VARCHAR (20) NOT NULL,
    equipe1 VARCHAR (20) NOT NULL,
    equipe2 VARCHAR (20) NOT NULL
)
ENGINE=INNO_DB;